[package]
name = "pretty_assertions"
version = "0.1.0"
authors = ["Colin Kiegel <kiegel@gmx.de>"]

description = "Overwrite `assert_eq!` with a drop-in replacement, adding a colorful diff."
repository = "https://github.com/colin-kiegel/rust-pretty-assertions"
documentation = "https://docs.rs/pretty_assertions"

license = "MIT/Apache-2.0"
categories = ["development-tools"]
keywords = ["assert", "diff", "pretty", "color"]
readme = "README.md"

[dependencies]
difference = "1.0.0"
